services:

  postgres:
    image: postgres:17
    container_name: learnflow-postgres

    environment:
      POSTGRES_DB: learnflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - learnflow_postgres_data:/var/lib/postgresql/data

volumes:
  learnflow_postgres_data: